name: Windows build

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release
      - name: Publish
        run: dotnet publish --configuration Release --no-build --no-restore
      - uses: papeloto/action-zip@v1
        with:
          files: D:\a\SixKeysOfTangrin\SixKeysOfTangrin\SixKeysOfTangrin\bin\Release\net5.0\publish\
          dest: SixKeysOfTangrin.zip
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ github.workspace }}/SixKeysOfTangrin.zip